services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_HOST}:3306"   # expõe o MySQL no host
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      retries: 10
      start_period: 60s

  api:
    build: .
    restart: always
    env_file: 
      - .env
    ports:
      - "8080:8080"  # Mapeia a porta da API
    environment:
      DB_HOST: mysql      # força o host correto (nome do serviço)
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 3306       # usa a porta interna do MySQL
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data: